#include "init.h"
#include <stdint.h>
void GPIO_init__Memory(void){};

void GPIO_InitLEDPB0 (void)
{
   SET_BIT(RCC->AHB1ENR, RCC_AHB1ENR_GPIOBEN | RCC_AHB1ENR_GPIOCEN);
   SET_BIT(GPIOB->MODER, GPIO_MODER_MODE0_0);
   CLEAR_BIT(GPIOB->OTYPER,GPIO_OTYPER_OT_0);
   SET_BIT(GPIOB->OSPEEDR, GPIO_OSPEEDER_OSPEEDR0_0);
   SET_BIT(GPIOB->BSRR, GPIO_BSRR_BR0);
}

void GPIO_InitBtnPC12(void)
{
    CLEAR_BIT(GPIOC->MODER, GPIO_MODER_MODE12_0);
    CLEAR_BIT(GPIOC->PUPDR, GPIO_PUPDR_PUPDR12_0);
}

